### ISSUE TITLE
App.paylike.io is offline

### ISSUE THREAD

**Issue by afanasy** [paylike/sdk#4] opened 2016-03-21 04:04 UTC
<img width="1365" alt="screen shot 2016-03-21 at 12 02 19" src="https://cloud.githubusercontent.com/assets/677646/13910425/f646274a-ef5c-11e5-8701-52ff483c57ba.png">

**Comment by tjconcept** [comment] 2016-03-22 08:40
Hi @afanasy 

We have had a similar bug report recently and is investigating the issue. I am not immediately able to reproduce it though. Could you try hard-refreshing, and posting the result of a `$ dig app.paylike.io`?

**Comment by afanasy** [comment] 2016-03-22 08:50
Hard refresh doesn't help

```
macBook:~ afanasy$ dig app.paylike.io

; <<>> DiG 9.8.3-P1 <<>> app.paylike.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 17656
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 2, ADDITIONAL: 2

;; QUESTION SECTION:
;app.paylike.io.            IN  A

;; ANSWER SECTION:
app.paylike.io.     272 IN  A   104.20.9.147
app.paylike.io.     272 IN  A   104.20.8.147

;; AUTHORITY SECTION:
paylike.io.     86372   IN  NS  tony.ns.cloudflare.com.
paylike.io.     86372   IN  NS  karina.ns.cloudflare.com.

;; ADDITIONAL SECTION:
tony.ns.cloudflare.com. 14559   IN  A   173.245.59.240
karina.ns.cloudflare.com. 19051 IN  A   173.245.58.178

;; Query time: 78 msec
;; SERVER: 10.11.0.1#53(10.11.0.1)
;; WHEN: Tue Mar 22 16:50:08 2016
;; MSG SIZE  rcvd: 153


```

**Comment by tjconcept** [comment] 2016-03-22 09:12
Even with those same IP's, I am not able to reproduce it.
I have tried a complete purge at CloudFlare, could you give it another shot?

**Comment by tjconcept** [comment] 2016-03-22 10:07
This should be fixed now. Thanks.

**Closed as completed by tjconcept** 2016-03-22 10:07 UTC

**Comment by flowocap** [comment] 2016-03-27 22:18
Right
